version: "3"
services:
  db:
    image: mysql:latest
    container_name: db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: $DB_PASSWORD
      MYSQL_DATABASE: $DB_NAME
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $USER_PASSWORD
    volumes:
      - ./data:/docker-entrypoint-initdb.d/
      - ./data2:/var/lib/mysql

  app:
    build: .
    container_name: app
    volumes:
      - ./app:/usr/src/app
    command: python3 main.py
